version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./www:/www
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - www-network
    php:
        build: './php'
        volumes:
            - ./www:/www
            - ./php.ini:/usr/local/etc/php/php.ini
        networks:
            - www-network

networks:
    www-network:
        driver: bridge
